name: AWS DEPLOY TO STAGING
# turn off deploy to AWS

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.AWS_DB_HOST }}
      DB_PW: ${{ secrets.AWS_DB_PW}}
      DB_USER: ${{ secrets.AWS_DB_USER }}
      DB_NAME: ${{ secrets.AWS_DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      COHERE_API_KEY: ${{ secrets.AWS_API_KEY }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v1
      - run: npm install

      - run: |
          touch .env
          echo DB_HOST = "$DB_HOST" >> .env
          echo DB_PW = "$DB_PW" >> .env
          echo DB_USER = "$DB_USER" >> .env
          echo DB_NAME = "$DB_NAME" >> .env
          echo SECRET_KEY = "$SECRET_KEY" >> .env
          echo COHERE_API_KEY = "$COHERE_API_KEY" >> .env

      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete --exclude node_modules"
          SOURCE: "deploy/"
          REMOTE_HOST: "ec2-18-218-107-33.us-east-2.compute.amazonaws.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/QuizApp-backend"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@ec2-18-218-107-33.us-east-2.compute.amazonaws.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            echo "Changing directory at $(date -u)"
            cd nodeapps/QuizApp-backend
            ls

            echo "npm install at $(date -u)"
            npm install --verbose
            
            echo "sudo systemctl at $(date -u)"
            sudo systemctl stop QuizApp-backend
            
            echo "copy at $(date -u)"
            sudo cp QuizApp-backend.service /lib/systemd/system/QuizApp-backend.service
            
            echo "systemctl reload at $(date -u)"
            sudo systemctl daemon-reload
            
            echo "systemctl start at $(date -u)"
            sudo systemctl start QuizApp-backend
            sudo systemctl status QuizApp-backend
